Migrate dependency management to Poetry
OpenLEADR/openleadr-python pull request #152
Opened 2023-02-09 17:13 UTC by allanlewis

This PR migrates the metadata and dependency management to `pyproject.toml` and [Poetry](https://python-poetry.org/).

2023-02-09 17:22 UTC, stan-janssen requested changes

2023-02-09 17:22 UTC, stan-janssen commented on .github/workflows/test-suite.yml
> +        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
I think you need to quote `3.10`, because at the moment this is getting cast to `3.1` and that makes the Github actions fail.

2023-02-10 10:34 UTC, allanlewis commented
One thing I haven't checked is whether Poetry is including the files described in `MANIFEST.in`. I don't think it uses that file so we should probably delete it, but we might need to give Poetry some extra config to include those files; or it might just work.

2023-02-21 14:58 UTC, allanlewis commented
@stan-janssen Are you able to test this change? I don't know enough about the project to test it beyond what you've configured in CI; the latter needs approval to run.

2023-03-07 17:20 UTC, allanlewis commented
Is someone able to test this change?

2023-03-28 06:11 UTC, stan-janssen commented
@allanlewis sorry about not getting back to this earlier. I’ll be testing it this week, thanks!

2023-10-16 16:14 UTC, allanlewis commented
Rebased on `main`.

2023-10-16 16:15 UTC, allanlewis commented
@stan-janssen are you able to take a look at this?

2024-04-25 10:38 UTC, allanlewis commented
Closing for lack of interest.

2024-04-25 10:38 UTC, closed without merging